var app = new Vue({
    el:"#app",
    data:{
        foodList:[{
            name:"炸鸡",
            price:20,
            discount:0.9
        },
        {
        name:"可乐",
        price:6,
        discount:0.9
        },
        {
        name:"薯条",
        price:8,
        discount:null
        },
        ]}
})